language: android

android:
  components:
    - platform-tools
    - build-tools-27.0.0
    - android-27
    - extra-android-m2repository
    - extra-android-support

script:
  - ./gradlew build

before_install:
  - chmod +x gradlew