language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-27

    # Extras
    - extra-android-support
    - extra-android-m2repository

    # System images to test
    - sys-img-armeabi-v7a-android-27